{
 "title": "Collectd",
 "tags": [
  "graphite",
  "collectd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": "collectd.*" },
   { "name": "disk", "query": "collectd.$host.disk*" },
   { "name": "interface", "query": "collectd.$host.interface*" },
   { "name": "df", "query": "collectd.$host.df-*" },
   { "name": "disk_plugin", "query": "disk_octets,disk_ops,disk_time" }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AVG CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "absolute(offset(groupByNode(collectd.$host.cpu-*.cpu-idle, 3, 'avg'), -100))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(absolute(offset(collectd.$host.cpu-*.cpu-idle, -100)), 2)"
    }
   ]
  },
  {
   "title": "CPU Wait",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.cpu-*.cpu-wait, 2)"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.cpu-*.cpu-system, 2)"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.cpu-*.cpu-user, 2)"
    }
   ]
  },
  {
   "title": "CPU Steal",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.cpu-*.cpu-steal, 2)"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(collectd.$host.load.load.*)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(aliasSub(sortByTotal(collectd.$host.memory.*), 'memory-(.*)', '\\1'))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "exclude(sortByName(groupByNodes(collectd.$host.cpu-*.*, 'avg', 3), true), 'idle')"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.swap.swap-cached, 3)"
    },
    {
     "target": "aliasByNode(collectd.$host.swap.swap-free, 3)"
    },
    {
     "target": "aliasByNode(collectd.$host.swap.swap-used, 3)"
    }
   ]
  },
  {
   "title": "Swap troughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.$host.swap.swap_io-in, 3)"
    },
    {
     "target": "aliasByNode(collectd.$host.swap.swap_io-out, 3)"
    }
   ]
  },
  {
   "title": "$disk_plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "disk_plugin",
   "collapsed": true,
   "panels": [
    {
     "title": "$disk Octets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "repeat": "disk",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(collectd.$host.$disk.$disk_plugin.*)"
      }
     ]
    },
    {
     "title": "$disk Octets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(collectd.$host.$disk.$disk_plugin.*)"
      }
     ]
    },
    {
     "title": "$disk Octets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(collectd.$host.$disk.$disk_plugin.*)"
      }
     ]
    },
    {
     "title": "$disk Octets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(collectd.$host.$disk.$disk_plugin.*)"
      }
     ]
    },
    {
     "title": "$disk Octets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "target": "aliasByMetric(collectd.$host.$disk.$disk_plugin.*)"
      }
     ]
    }
   ]
  },
  {
   "title": "DF Complex $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "repeat": "df",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 56 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_complex*, '.*df_complex-(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "DF Inodes $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 78 },
     "repeat": "df",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 78 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 99 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$df",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 120 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$df.df_inodes-*, '.*inodes-(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Octets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 121 },
     "repeat": "interface",
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 121 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 121 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 127 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 127 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 133 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 133 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 133 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 139 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 139 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 145 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 145 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 145 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 151 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 151 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 151 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 157 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_octets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 158 },
     "repeat": "interface",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 158 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 158 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 165 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 165 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 165 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 172 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 172 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 172 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 179 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 179 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 179 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 186 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 186 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 193 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 193 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 200 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_packets.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 201 },
     "repeat": "interface",
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 201 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 201 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 208 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 208 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 208 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 215 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 215 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 215 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 222 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 222 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 222 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 229 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 229 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 229 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 236 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 236 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 236 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 243 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_errors.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "Interface Drops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$interface",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 244 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "target": "aliasSub(collectd.$host.$interface.if_dropped.*, '.*$host.interface-(.*)', '\\1')"
      }
     ]
    }
   ]
  }
 ]
}