{
 "title": "Go Carbon",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Carbon Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.disk*, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.cache_requests, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Cache Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.cache_hit, 4, 'sum')"
    },
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.cache_miss, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Cache Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.cache*_ns, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Index Build Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 4 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.index_build_time_ns, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Render Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.carbonserver.render_*, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Size vs Overflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.cache.overflow, 4, 'sum')"
    },
    {
     "target": "groupByNode(carbon.agents.*.cache.size, 4, 'sum')"
    },
    {
     "target": "groupByNode(carbon.agents.*.cache.maxSize, 4, 'sum')"
    }
   ]
  },
  {
   "title": "TCP Receiver",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.tcp.*, 4, 'sum')"
    }
   ]
  },
  {
   "title": "Persister",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(carbon.agents.*.persister.*, 4, 'sum')"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 } }
 ]
}