{
 "title": "HPDP Pools",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "CellServer", "label": "Cell Server", "query": "hpdp.*" },
   { "name": "Pool", "label": "Pool", "query": "hpdp.$CellServer.pool.*" }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Media",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(hpdp.$CellServer.pool.$Pool.*, '.*.pool.(.*)', '\\1')"
    }
   ]
  },
  { "title": "$Pool stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "Pool" },
  {
   "title": "Total Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.media"
    }
   ]
  },
  {
   "title": "$Pool Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 9 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(hpdp.$CellServer.pool.$Pool.media_list.*.used_mb)"
    }
   ]
  },
  {
   "title": "$Pool Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 9 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(hpdp.$CellServer.pool.$Pool.media_list.*.total_mb)"
    }
   ]
  },
  {
   "title": "Free Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.free"
    }
   ]
  },
  {
   "title": "Appendable Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.appendable"
    }
   ]
  },
  {
   "title": "Full Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.full"
    }
   ]
  },
  {
   "title": "Good Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.good"
    }
   ]
  },
  {
   "title": "Fair Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.fair"
    }
   ]
  },
  {
   "title": "Poor Media",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "hpdp.$CellServer.pool.$Pool.poor"
    }
   ]
  }
 ]
}