{
 "title": "HPDP Sessions",
 "time": { "from": "now-28d", "to": "now" },
 "templating": {
  "list": [
   { "name": "CellServer", "label": "Cell Server", "query": "hpdp.*" },
   { "name": "Group", "label": "Group", "query": "hpdp.$CellServer.session.*" },
   {
    "name": "Job",
    "label": "Job",
    "query": "hpdp.$CellServer.session.$Group.*"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Written",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "mbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "groupByNode(hpdp.$CellServer.session.*.*.written, 5, 'sum')"
    }
   ]
  },
  {
   "title": "Total Written per Group",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "target": "groupByNode(hpdp.$CellServer.session.*.*.written, 3, 'sum')"
    }
   ]
  },
  { "title": "Sessions Per Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Session Written",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "mbytes", "label": "Written" }
   ],
   "targets": [
    {
     "target": "aliasSub(hpdp.$CellServer.session.$Group.$Job.written, '.*session.(.*)', '\\1')"
    },
    {
     "target": "aliasSub(hpdp.$CellServer.session.$Group.$Job.duration, '.*session.(.*)', '\\1')"
    }
   ]
  },
  { "title": "Files and Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "File Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.files, 4)"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasSub(hpdp.$CellServer.session.$Group.$Job.objects, '.*session.(.*)', '\\1')"
    },
    {
     "target": "aliasSub(hpdp.$CellServer.session.$Group.$Job.fails, '.*session.(.*)', '\\1')"
    },
    {
     "target": "aliasSub(hpdp.$CellServer.session.$Group.$Job.completes, '.*session.(.*)', '\\1')"
    }
   ]
  },
  { "title": "Job Size and Retention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Session Written",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.written, 4)"
    }
   ]
  },
  {
   "title": "Retention Period",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.retention, 4)"
    }
   ]
  },
  { "title": "Job Counter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Session Failures",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.fails, 4)"
    }
   ]
  },
  {
   "title": "Session Errors",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.errors, 4)"
    }
   ]
  },
  {
   "title": "Session Warnings",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "target": "aliasByNode(hpdp.$CellServer.session.$Group.$Job.warnings, 4)"
    }
   ]
  }
 ]
}