{
 "title": "Telegraf",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "telegraf.*" },
   {
    "name": "disk",
    "label": "Disk",
    "query": "telegraf.$host.diskio.[v,s][a-z][a-z]*"
   },
   { "name": "interface", "label": "Interface", "query": "telegraf.$host.net.[^all]*" }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "telegraf.$host.system.n_users" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "target": "telegraf.$host.system.uptime" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "sum(exclude(telegraf.$host.cpu.cpu-total.*, 'idle'))"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(exclude(telegraf.$host.disk.*.*.*.*.total, 'devtmpfs'), 6), '-', '/')"
    }
   ]
  },
  {
   "title": "Disk Usage Percent",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(exclude(telegraf.$host.disk.*.*.*.*.used_percent, 'devtmpfs'), 6), '-', '/')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "telegraf.$host.processes.total" }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "target": "telegraf.$host.mem.total" }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "telegraf.$host.system.n_cpus" }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "AVG CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasSub(exclude(telegraf.$host.cpu.cpu-total.*, 'idle'), '.*usage_(.*)', '\\1')"
      }
     ]
    },
    {
     "title": "AVG CPU usage per core",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "target": "aliasSub(groupByNode(exclude(telegraf.$host.cpu.cpu[0-9]*.*, 'idle'), 3, 'sum'), '.*usage_(.*)', '\\1')"
      }
     ]
    }
   ]
  },
  {
   "title": "Load/Mem/Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.system.load*, 3)"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.mem.total, 3)"
      },
      {
       "target": "aliasByNode(telegraf.$host.mem.used, 3)"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.swap.used_percent, 3)"
      },
      {
       "target": "aliasByNode(perSecond(telegraf.$host.swap.in), 3)"
      },
      {
       "target": "aliasByNode(perSecond(telegraf.$host.swap.out), 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Telegraf Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent Gather Errors",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "telegraf.$host.internal_agent.gather_errors"
      }
     ]
    },
    {
     "title": "Agent Metrics Dropped",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "telegraf.$host.internal_agent.metrics_dropped"
      }
     ]
    },
    {
     "title": "Agent Metrics Gathered",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "perSecond(telegraf.$host.internal_agent.metrics_gathered)"
      }
     ]
    },
    {
     "title": "Agent Metrics Written",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "target": "perSecond(telegraf.$host.internal_agent.metrics_written)"
      }
     ]
    },
    {
     "title": "Metrics Gather time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.internal_gather.*.gather_time_ns, 3)"
      }
     ]
    },
    {
     "title": "Output Write Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.internal_write.graphite.write_time_ns, 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Througput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Througput $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "repeat": "disk",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.read_bytes), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.write_bytes), 'write')"
      }
     ]
    },
    {
     "title": "Througput $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.read_bytes), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.write_bytes), 'write')"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IOPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "IOPs $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "repeat": "disk",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.reads), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.writes), 'write')"
      }
     ]
    },
    {
     "title": "IOPs $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.reads), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.writes), 'write')"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "repeat": "disk",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.read_time), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.write_time), 'write')"
      }
     ]
    },
    {
     "title": "Time $disk",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.read_time), 'read')"
      },
      {
       "target": "alias(perSecond(telegraf.$host.diskio.$disk.write_time), 'write')"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
     "repeat": "interface",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    },
    {
     "title": "Interface $interface",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(telegraf.$host.net.$interface.*), 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "S.M.A.R.T",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk SMART Temperature",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.smart_device.*.*.Enabled.*.*.*.temp_c, 4, 6, 7)"
      }
     ]
    },
    {
     "title": "Health",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.smart_device.*.*.Enabled.*.*.*.health_ok, 4, 6, 7)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "aliasByNode(telegraf.$host.ping.*.*, 3, 4)"
      }
     ]
    }
   ]
  }
 ]
}