{
 "title": "ZFS on Linux",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "query": "zfs.*" },
   { "name": "pool", "query": "zfs.$host.pool.*" }
  ]
 },
 "panels": [
  { "title": "ARC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ARC Used",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    { "target": "zfs.$host.arc.size" }
   ]
  },
  {
   "title": "ARC Hit ratio",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(derivative(zfs.$host.arc.hits), #C)",
     "targetFull": "asPercent(derivative(zfs.$host.arc.hits), sumSeries(group(derivative(zfs.$host.arc.hits), derivative(zfs.$host.arc.misses))))"
    }
   ]
  },
  {
   "title": "ARC Hits/Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(zfs.$host.arc.hits), 3)"
    },
    {
     "target": "aliasByNode(perSecond(zfs.$host.arc.misses), 3)"
    }
   ]
  },
  {
   "title": "ARC Size by Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(zfs.$host.arc.data.size, 3)"
    },
    {
     "target": "aliasByNode(zfs.$host.arc.metadata.size, 3)"
    },
    {
     "target": "aliasByNode(zfs.$host.arc.other.size, 3)"
    },
    {
     "target": "aliasByNode(zfs.$host.arc.anon.size, 3)"
    },
    {
     "target": "aliasByNode(zfs.$host.arc.hdr.size, 3)"
    },
    {
     "target": "aliasByMetric(zfs.$host.arc.size)"
    }
   ]
  },
  {
   "title": "L2ARC Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "L2ARC Used",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      { "target": "zfs.$host.arc.l2.size" }
     ]
    },
    {
     "title": "ARC Hit ratio",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "target": "asPercent(derivative(zfs.$host.arc.l2.hits), #C)",
       "targetFull": "asPercent(derivative(zfs.$host.arc.l2.hits), sumSeries(group(derivative(zfs.$host.arc.hits), derivative(zfs.$host.arc.misses))))"
      }
     ]
    },
    {
     "title": "ARC Hits/Misses",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(zfs.$host.arc.l2.hits), 4)"
      },
      {
       "target": "aliasByNode(perSecond(zfs.$host.arc.l2.misses), 4)"
      }
     ]
    },
    {
     "title": "L2ARC Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "aliasByNode(perSecond(zfs.$host.arc.l2.read.bytes), 4)"
      },
      {
       "target": "aliasByNode(perSecond(zfs.$host.arc.l2.write.bytes), 4)"
      }
     ]
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Througput $pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(zfs.$host.pool.$pool.bytes.read), 5)"
    },
    {
     "target": "aliasByNode(perSecond(zfs.$host.pool.$pool.bytes.write), 5)"
    }
   ]
  },
  {
   "title": "IOPs $pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(zfs.$host.pool.$pool.iops.read), 5)"
    },
    {
     "target": "aliasByNode(perSecond(zfs.$host.pool.$pool.iops.write), 5)"
    }
   ]
  },
  {
   "title": "Latency $pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(perSecond(scale(zfs.$host.pool.$pool.time.read, 0.125)), 5)"
    },
    {
     "target": "aliasByNode(perSecond(scale(zfs.$host.pool.$pool.time.write, 0.125)), 5)"
    }
   ]
  }
 ]
}